Feature/esther/cns 22 internet file service upload file
Esther125/CloudDrop pull request #12
Opened 2024-11-10 11:20 UTC by Esther125

## Changes
- Implement file upload function.

## Tests
- Download [Postman](https://www.postman.com/downloads/)
- Setting up Postman as the picture below and upload any file to test the API endpoint. You will get a unique fileId if success. You can also check if the file you uploaded is really saved under the path: `backend/uploads`
![image](https://github.com/user-attachments/assets/554fafd3-52f0-43a8-8020-2f137d55fd5b)

2024-11-10 14:28 UTC, yun-si requested changes
如果沒有檔案上傳，會回傳 400 沒錯
但 app 會 crash
但應該是要避免 app crash 的

<img width="540" alt="截圖 2024-11-10 晚上10 25 38" src="https://github.com/user-attachments/assets/73d17e29-6835-46d5-964b-368c92f86f2e">

2024-11-18 10:58 UTC, yun-si commented
上面的問題解決了！
只是還有一些 coding style 的部分，例如：使用箭頭函數，還有 conflict 要解一下～

```
async upload(req, res) {}
```
->
```
upload = async  (req, res) => {}
```

2024-11-18 11:01 UTC, yun-si commented on backend/src/services/internetFileService.js
> +        const __filename = fileURLToPath(import.meta.url);
想問問：為什麼這裡會用兩個底線開頭，命名這個變數

2024-11-23 18:36 UTC, Esther125 commented on backend/src/services/internetFileService.js
> +        const __filename = fileURLToPath(import.meta.url);
這是 node.js 的習慣，那兩個變數算是比較特別的變數

2024-11-24 06:24 UTC, yun-si commented on backend/src/controllers/internetFileController.js
> +        this.download = this.download.bind(this);
用了箭頭函數就不需要這兩行了

2024-11-24 06:32 UTC, yun-si approved these changes
lgtm~~

2024-11-24 06:42 UTC, merged