Feature/jlin/cns 27 API document
Esther125/CloudDrop pull request #13
Opened 2024-11-11 11:36 UTC by JLin056

## Change
Add API document.

2024-11-11 14:59 UTC, yun-si requested changes

2024-11-11 14:59 UTC, yun-si commented on docs/assets/system design/API 架構.jpg
資料夾盡量不要有空格
改成底線比較好～

2024-11-11 14:59 UTC, yun-si commented on docs/planning-02/api.md
> +分成 房間建置 和 離開
總共有三種
create, join, leave

2024-11-11 14:59 UTC, yun-si commented on docs/planning-02/api.md
> +-   Staging-area：資料下載（download）
個人檔案暫存區有兩個 api
一個是獲取暫存區資料的，一個是下載

2024-11-11 14:59 UTC, yun-si commented on docs/planning-02/api.md
> +分成 註冊 和 登入
這裡也有三種
第一個是進入主頁後要給使用者一個 id的 api (/api/v1/)，以及登入，註冊

剛剛想到有登入那也會有登出，所以可能圖也要再加一個
總共四個

2024-11-11 14:59 UTC, yun-si commented on docs/planning-02/api.md
> +-   History：檔案傳輸歷史紀錄區
同個人檔案暫存區

2024-11-11 14:59 UTC, yun-si commented on docs/planning-02/api.md
<img width="857" alt="image" src="https://github.com/user-attachments/assets/4aa81d14-084c-40a8-bb0f-0f19ff856aa6">
可以比照上面這個圖在主頁的 readme 新增嗎？
然後把 api.md 放進 planning 資料夾，不要新增新的 planning-02

2024-11-11 17:48 UTC, amyhsu-o requested changes

2024-11-11 17:48 UTC, amyhsu-o commented on docs/planning-02/api.md
可以順便把上（小組作業）下（如何開始）的點的距離改成一樣的~

2024-11-12 03:56 UTC, amyhsu-o requested changes

2024-11-12 03:56 UTC, amyhsu-o commented on docs/assets/system design/API 架構.jpg
舊的沒有用到可以刪掉

2024-11-12 03:56 UTC, amyhsu-o commented on docs/planning-02/api.md
舊的沒有用到可以刪掉

2024-11-12 13:07 UTC, amyhsu-o approved these changes, later dismissed

2024-11-12 13:28 UTC, yun-si submitted a review, later dismissed

2024-11-12 13:35 UTC, amyhsu-o approved these changes
lgtm
（readme 點距可以改一樣就好了..，或是以後再改也可以~）

2024-11-12 13:43 UTC, merged