Feature/yun si/cns 26 room service join room and redis
Esther125/CloudDrop pull request #18
Opened 2024-11-16 18:09 UTC by yun-si

### Changes
- Modify redisClient
  - Add `key: set` related function
- Add joinRoom in RoomService
- Modify room controller and route
- Unified log format [can be discuss in meeting]
- See new data format from the [page](https://esther125.atlassian.net/wiki/spaces/CNSP/pages/17268770/Redis)

### Test
1. open redis server
2. run command below

  ```
  cd backend
  npm install
  npm start
  ```
3. following the steps below to test the apis 

create room for user id 0001
<img width="1033" alt="截圖 2024-11-17 凌晨12 58 15" src="https://github.com/user-attachments/assets/ff1c3946-37ea-4cca-9105-142b63239248">

log format
<img width="520" alt="截圖 2024-11-17 凌晨12 58 59" src="https://github.com/user-attachments/assets/25aacc9e-ce1d-4b1c-ae46-005e2a17ca62">

user id 0002 join room created by 0001
(can see room members in response)
<img width="1039" alt="截圖 2024-11-17 凌晨12 59 33" src="https://github.com/user-attachments/assets/a1427747-4b8e-4311-9286-7df64dc50844">

user id 0002 join room created by 0001 "**again**"
(message will change)
<img width="1039" alt="截圖 2024-11-17 凌晨12 59 46" src="https://github.com/user-attachments/assets/fb488531-2736-4922-8347-78fe13993922">

create room for another user id 0009
<img width="1034" alt="截圖 2024-11-17 凌晨1 00 02" src="https://github.com/user-attachments/assets/df14c447-d286-424c-9d45-f1a0ae9d6967">

user id 0002 change to join room created by 0009
<img width="1036" alt="截圖 2024-11-17 凌晨1 00 25" src="https://github.com/user-attachments/assets/6803fe77-a548-4c07-88b8-7dd974cf76d4">

keys in redis
<img width="204" alt="截圖 2024-11-17 凌晨1 00 44" src="https://github.com/user-attachments/assets/07f1594b-6f74-4f91-ab87-497d3ba00faf">

members in each room
<img width="243" alt="截圖 2024-11-17 凌晨1 01 24" src="https://github.com/user-attachments/assets/e18b2662-0174-4c5a-98b7-023dc4b487d0">

2024-11-21 02:09 UTC, amyhsu-o requested changes

2024-11-21 02:09 UTC, amyhsu-o commented on backend/src/controllers/roomsController.js
> +            res.status(500).json({ mesage: `Error when creating room for ${user.id}` });
typo: mesage -> message

2024-11-21 02:09 UTC, amyhsu-o commented on backend/src/controllers/roomsController.js
> +            res.status(500).json({ mesage: `Error when when joining room ${token} for user ${user.id}` });
typo: mesage -> message

2024-11-21 02:09 UTC, amyhsu-o commented on backend/src/services/roomsService.js
> +        members = { userId };
這樣寫的話內容會是（假設 userID = "0001"）
members = {
    userId: "0001"
}
的 object，不會是 set

所以會變成第一次新增 user 的時候顯示
<img width="313" alt="image" src="https://github.com/user-attachments/assets/c5612e9a-377b-4922-9371-cd4ed8906bdc">
第二次顯示
<img width="326" alt="image" src="https://github.com/user-attachments/assets/916a8c44-f859-429d-b464-74a5873cf363">
2 次的 members 不一樣，第二次回傳的 roomObj 才是 Redis 裡面實際存的形式

2024-11-21 02:09 UTC, amyhsu-o commented on backend/src/services/roomsService.js
> +    joinRoom = async (userId, token) => {
joinRoom 是不是應該限制只能加入已經有人的 room，目前好像是不管有沒有這個 room，都可以透過 joinRoom 加入

2024-11-21 03:28 UTC, JLin056 reviewed
上次開會有提到，有幫測了 userid 放空值、亂碼、表情符號，是會create room 跟 join room 成功的，但不確定有沒有判斷必要
<img width="460" alt="image" src="https://github.com/user-attachments/assets/93f0d655-6b0c-43aa-87b6-f16d7ce68e52">

2024-11-22 10:51 UTC, amyhsu-o requested changes

2024-11-22 10:51 UTC, amyhsu-o commented on backend/src/controllers/roomsController.js
> +            res.status(500).json({ message: `Error when creating room for ${user.id}` });
如果 const user 寫在 try block 裡這邊會抓不到 user.id

2024-11-22 10:51 UTC, amyhsu-o commented on backend/src/controllers/roomsController.js
> +            res.status(500).json({ message: `Error when when joining room ${token} for user ${user.id}` });
如果 const user 和 const token 寫在 try block 裡這邊會抓不到 user.id 和 token

2024-11-22 10:54 UTC, amyhsu-o commented
> 上次開會有提到，有幫測了 userid 放空值、亂碼、表情符號，是會create room 跟 join room 成功的，但不確定有沒有判斷必要 <img alt="image" width="460" src="https://private-user-images.githubusercontent.com/149258151/388342107-93f0d655-6b0c-43aa-87b6-f16d7ce68e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzI5ODAsIm5iZiI6MTczMjI3MjY4MCwicGF0aCI6Ii8xNDkyNTgxNTEvMzg4MzQyMTA3LTkzZjBkNjU1LTZiMGMtNDNhYS04N2I2LWYxNmQ3Y2U2OGU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMDUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjAzNzA4N2U3MTU1MDkxODI5ZDMxNTBjMmY2ZTMwMGIzMTBiNTI0ZWNkODZlMzExY2EwMzFjMzYwYWMwMmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._u7uq7li6e_1F6FbHnmKKeiXVU_5Li7njEReqlxnpoc">
亂碼、表情符號這些應該要等寫了發 userID 的規則之後，才有辦法加，到時候可能要寫個判斷是不是 valid userID 的 function 給大家用

2024-11-22 11:20 UTC, yun-si commented on backend/src/controllers/roomsController.js
> +            res.status(500).json({ message: `Error when when joining room ${token} for user ${user.id}` });
<img width="870" alt="image" src="https://github.com/user-attachments/assets/5dcd11b7-3476-4202-aaf2-dd2a2b88167e">

fixed! thanks

2024-11-22 12:54 UTC, amyhsu-o approved these changes

2024-11-22 12:58 UTC, merged