Feature/yu mei/cns 20 chat api
Esther125/CloudDrop pull request #20
Opened 2024-11-17 17:32 UTC by amyhsu-o

## Changes

- Add server-side websocket logic for chatroom
- Add integration tests for websocket server covering 
    1. connect to server
    2. join chatrooms
    3. message exchange in chatroom
    4. message exchange between client and server
- Add API design doc for websocket for chatroom

## Tests

### About test

simulate some client-side actions to the server to check the interaction between clients and the server, and  verify if the response structure and contents meet our expectations.

You can see the API design of websocket for chatroom in [/docs/planning/api.md](https://github.com/Esther125/CloudDrop/blob/feature/yu-mei/CNS-20_chat_api/docs/planning/api.md).

### How to run the test

use one terminal to open the backend server

```bash
# start backend
cd backend
npm install
npm start
```

use another terminal to run the integration test

```bash
# run integration test
cd backend
npm run test
```

### Expected results

If all the tests are passed, the result in testing terminal will be "PASS".
![image](https://github.com/user-attachments/assets/9115b1e9-67fc-45d0-bf7f-462109e8667a)

You can scroll up in testing terminal to see what client really get in each test.
![image](https://github.com/user-attachments/assets/8cc1fa72-38eb-4997-95ce-29a5b028c8fd)

Log in backend server terminal.
![image](https://github.com/user-attachments/assets/90849325-e868-458a-aee6-c078808edb60)

You can comment out some test in [/backend/src/tests/integration/websocketChat.test.js](https://github.com/Esther125/CloudDrop/blob/feature/yu-mei/CNS-20_chat_api/backend/tests/integration/websocketChat.test.js) to see the relationship between server and client via the API designed in [/docs/planning/api.md](https://github.com/Esther125/CloudDrop/blob/feature/yu-mei/CNS-20_chat_api/docs/planning/api.md) .

2024-11-19 14:43 UTC, yun-si requested changes

2024-11-19 14:43 UTC, yun-si commented on backend/index.js
> +import http from 'http';
應該也可以用 https ，但想了想如果目前預計前後端會開在同一個 ec2 instance，那可能不太需要

之後有需要（後端對外提供服務，不是在同一個 instance 內）再開一張票改吧

2024-11-19 14:43 UTC, yun-si commented on backend/src/tests/integration/websocketChat.test.js
通常 test 不會放在 src 裡面，而是跟 src 在同一層，可以移動一下
Eg.
```
backend
├── index.js
├── package-lock.json
├── package.json
├── src
│   └── ...
└── tests
    └── integration
        └── websocketChat.test.js
```

2024-11-19 14:43 UTC, yun-si commented on backend/package.json
> +    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",
<img width="458" alt="image" src="https://github.com/user-attachments/assets/a6890722-0aa2-4035-8dcd-94f6191674d8">

跑指令的時候有看到這個警告，覺得先不要用 experimental feature 比較好，可以換一下嗎？
如果沒有可以替代的，也可以暫時用這個

2024-11-22 15:50 UTC, amyhsu-o commented
## Changes

- change testing package (jest -> mocha + chai)
- move `test` directory from `src` to `backend` (since mocha can only read files in the first level of folder name `test`, so remove folder `integration`)
- change chatroomName to roomToken
- merge notification ( #21 ) into chat

2024-11-23 00:37 UTC, yun-si commented
> ## Changes
> * move `test` directory from `src` to `backend` (since mocha can only read files in the first level of folder name `test`, so remove folder `integration`)

那可以把 integration 加在 檔案名稱裡嗎
`websocketChat.integration.test.js`
大概這樣

2024-11-23 01:06 UTC, yun-si requested changes

2024-11-23 01:06 UTC, yun-si commented on backend/src/services/chatService.js
> +    connectWrongFormat = (socket) => {
這裡可以傳入 userId ，在 log 的時候把 user id log 出來嗎
沒有的話，就只能知道有人失敗，但不知道是誰
還是其實不需要知道是誰？

2024-11-23 01:06 UTC, yun-si commented on backend/src/services/chatService.js
connect 的時候是 socket.join(userID);
joinChatRoom 的時候是 socket.join(roomToken);

如過 web socket 是透過 join 加入的話
那還需要 connect 這一步嗎？還是有 join chat room 其實就夠了？（我不太確定．你可以稍微解釋一下這樣寫的目的～

2024-11-23 01:06 UTC, yun-si commented on backend/src/services/chatService.js
> +    requestTransfer = (socket, roomToken, receiverID, chatNameSpace) => {
如果像要傳給整個 room 的人，receiverID 要填什麼？
還是需要一個迴圈每一個 in room 的呼叫一次

2024-11-23 01:06 UTC, yun-si commented on backend/src/services/chatService.js
> +        }
如果是一樣的處理 return false
可以考慮寫成下面這樣
```
        let memberSockets;
        let userSocket;
        try {
            memberSockets = [...socket.adapter.rooms.get(roomToken)];
            userSocket = [...socket.adapter.rooms.get(userID)][0];
        } catch {
            return false;
        }
```

2024-11-23 01:06 UTC, yun-si commented on backend/src/services/chatService.js
> +        );
是 error message 的話可以改用
`log.error`

2024-11-23 01:06 UTC, yun-si commented on backend/src/services/chatService.js
> +}
不太理解 disconnect 的功能
直觀上，disconnect 之後應該就取不到 user id
但這裡可以成功取 user id，並 log 出來
但也沒有其他後續操作
那麼這個 disconnect 還需要嗎？

2024-11-23 01:07 UTC, yun-si commented on backend/package.json
> +    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",
lgtm~

2024-11-29 16:07 UTC, amyhsu-o commented on backend/src/services/chatService.js
> +    connectWrongFormat = (socket) => {
```js
connect = (socket) => {
        // connect to server (/chat)
        console.log('[chatController] -----connect-----');

        let userID;
        try {
            userID = socket.handshake.auth.user.id;
        } catch {
            userID = null;
        }

        try {
            if (userID) {
                this.chatService.connect(socket, userID);
            } else {
                this.chatService.connectWrongFormat(socket);
            }
        } catch {
            console.error(`[chatController] Error when connecting chat websocket`);
        }
    };
```
這邊就是因為抓不到 userID 才會進 connectWrongFormat 的，所以沒有 userID

2024-11-29 16:12 UTC, amyhsu-o commented on backend/src/services/chatService.js
**connect**
- 使用時機：user 一進入網頁
- client 端的使用方法：
```js
const socket = io(`${serverURL}/chat`, {
    auth: {
        user: {
            id: userID;
        }
    }
});
```
- 目的：以後需要一對一傳輸的時候，讓 server 可以透過 userID 找到這個 client 的 socket

**joinChatroom**
- 使用時機：user 要求進入房間
- client 端的使用方法：
```js
socket.emit('join chatroom', { roomToken });
```
- 目的：以後需要對房間廣播的時候，讓 server 可以透過 roomToken 找到房間內所有 user 的 socket

2024-11-29 16:16 UTC, amyhsu-o commented on backend/src/services/chatService.js
> +}
**disconnect**

是在 socket 主動或意外和 server 斷線的時候會觸發，然後會帶有斷線的原因 reason（這個是 socket.io 提供的功能）
因為可以知道是哪一個 socket 斷線的，socket 裡又有帶 userID 的資訊，所以可以得到 userID 的資訊

**關於有沒有需要?**
可以拿來檢查/判斷為甚麼 user 收不到訊息、為甚麼斷線

2024-11-29 18:12 UTC, amyhsu-o commented on backend/src/services/chatService.js
> +    requestTransfer = (socket, roomToken, receiverID, chatNameSpace) => {
原本只有寫到一對一的，這次有加一對房間的傳輸了

2024-11-29 18:13 UTC, amyhsu-o commented on backend/src/services/chatService.js
> +        }
改了~

2024-11-29 18:13 UTC, amyhsu-o commented on backend/src/services/chatService.js
> +        );
改了~

2024-11-29 18:15 UTC, amyhsu-o commented
## Changes
1. add one to room transfer request
2. add **event: `room notify`** for notifying users in room when someone joining or leaving the room

2024-11-30 01:45 UTC, amyhsu-o commented
## Changes
1. add one to room transfer request
2. add **event: `room notify`** for notifying users in room when someone joining or leaving the room
3. add content in system message to show why fail

 (detail in [API](https://github.com/Esther125/CloudDrop/blob/feature/yu-mei/CNS-20_chat_api/docs/planning/api.md))

2024-11-30 06:14 UTC, yun-si approved these changes

2024-11-30 06:15 UTC, merged