Feature/yu mei/cns 33 dynamodb for user info
Esther125/CloudDrop pull request #26
Opened 2024-11-24 01:24 UTC by amyhsu-o

## Changes

- DynamoDB service for user info
- register and login logic in authService related to user info in DynamoDB

## Setup

- get access key in aws console 
1. search for IAM
2. click 'Users' in IAM resources
3. click 'Clouddrop-DynamoDB'
4. click 'Create access key'
![image](https://github.com/user-attachments/assets/c2793071-92ad-472d-bff8-91b0f07c0e2f)
5. follow `.env.example` to make the `.env` , and put the access key in it

## Test

Start backend server

```bash
cd backend
npm install
``` 

Use postman

### Test 1:  /register
![image](https://github.com/user-attachments/assets/2e5c3907-8696-48b0-b09b-d2b19fa241f4)

### Test 2: /login
![image](https://github.com/user-attachments/assets/cf715dc3-9809-4086-a04a-4378fc155f6a)

You can go to [DynamoDB in aws console](https://ap-northeast-1.console.aws.amazon.com/dynamodbv2/home?region=ap-northeast-1#item-explorer?maximize=true&table=userInfoRecord) to see the new data added in through the API. 
For user info, the structure store in DB is 

```js
{
    pk: USER#[userID]#INFO
    sk: INFO
    email: [email] 
    passwordSalt: [passwordSalt]
    passwordHash: [passwordHash]
    userName: [userName]
}
```

(There are currently some demonstration data in it.)

2024-11-29 15:21 UTC, yun-si requested changes

2024-11-29 15:21 UTC, yun-si commented on backend/.env.example
> +AWS_SECRET_ACCESS_KEY=
因為 s3 有一樣的變數名稱
改成
DYNAMODB_ACCESS_KEY_ID
DYNAMODB_SECRET_ACCESS_KEY
比較好～

2024-11-29 15:21 UTC, yun-si commented on backend/src/controllers/authController.js
> +            }
```
const { userID, email, password, userName } = req.body;
try {
    if (!userID || !email || !password || !userName) {
        const missingFields = [
            !userID && 'userID',
            !email && 'email',
            !password && 'password',
            !userName && 'userName',
        ].filter(Boolean);

        res.status(401).json({ message: `${missingFields.join(', ')} are required` });
        return;
    }
...
```
這樣寫比較簡潔～ 丟 gpt 產出來的

<img width="622" alt="image" src="https://github.com/user-attachments/assets/1a4027f7-d3a0-4054-8c57-42bffcd5fcd5">

2024-11-29 15:21 UTC, yun-si commented on backend/src/controllers/authController.js
> +            }
跟上面一樣～

2024-12-01 02:09 UTC, amyhsu-o commented on backend/.env.example
> +AWS_SECRET_ACCESS_KEY=
討論後決定 DynamoDB 和 S3 共用一個 IAM user，所以不改

2024-12-01 02:10 UTC, amyhsu-o commented on backend/src/controllers/authController.js
> +            }
改了。統一用 authController.js 裡的 _reqWithMissingValue() 來處理

2024-12-01 02:10 UTC, amyhsu-o commented on backend/src/controllers/authController.js
> +            }
改了。統一用 authController.js 裡的 _reqWithMissingValue() 來處理

2024-12-01 14:10 UTC, yun-si approved these changes, later dismissed

2024-12-01 15:45 UTC, yun-si approved these changes

2024-12-01 15:45 UTC, merged