Feature/jlin/cns 35 retrieve from s3 function
Esther125/CloudDrop pull request #28
Opened 2024-11-28 05:35 UTC by JLin056

## Change
- Add retrieve file from s3 function
- Add S3-related tests:
   - add retrieve file test: `S3Test.js`

## Tests
### About test
The test simulates generating a pre-signed URL for downloading a file from S3 to verify that the S3Service correctly generates URLs with the specified expiration time.

### How to run the test
1. Log in to AWS IAM (S3UploaderDownloader) and create access key
2. Add the generated access key and secret key to your .env file:
```
AWS_ACCESS_KEY_ID=your-access-key-id
AWS_SECRET_ACCESS_KEY=your-secret-access-key
S3_BUCKET_REGION=your-bucket-region
BUCKET_NAME=your-bucket-name
```
3. Navigate to the project directory and install dependencies
```
cd backend
npm install
```
4. Execute the test script:
```
node src/tests/s3/s3Test.js
```

### Expected results
If the file generate is successful, the result will include the message:
```
Presigned URL generated: {URL}
User generate presigned Url Success
```
< Note > : Due to safety issues, no pictures are posted.

2024-11-28 15:50 UTC, yun-si commented
解完 conflict 就可以了～

一個小小的問題， url 是不是不要 log 出來比較好啊，會不會有安全疑慮？可能 log 傳出去被一直 access 之類的，雖然我們只開一天

2024-11-29 15:29 UTC, yun-si commented
環境變數改一下名比較好，跟 dynamodb的做區分
然後記得寫在 .example.env 裡

S3_ACCESS_KEY_ID
S3_SECRET_ACCESS_KEY

2024-12-01 02:15 UTC, amyhsu-o commented
討論後決定 DynamoDB 和 S3 共用一個 IAM user，所以變數名稱不用改

2024-12-01 02:37 UTC, amyhsu-o requested changes

2024-12-01 02:37 UTC, amyhsu-o commented on backend/src/services/s3Service.js
> +dotenv.config(); // import .env variable
在 backend 裡，npm start 的 script 裡就已經有帶 `--env-file=.env` 了，所以合併之後不需要 dotenv，看要不要這裡先拿掉（拿掉的要 uninstall），然後在測試的時候改成 `node --env-file=.env src/tests/s3/s3Test.js`

2024-12-01 02:37 UTC, amyhsu-o commented on backend/src/services/s3Service.js
> +                secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
這裡如果有在 .env 寫
```
# AWS
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=
```

應該 S3Client 會自己抓（至少 DynamoDB 是這樣）

```js
this._client = new DynamoDBClient({});
```
.env 有這邊就可以不用放參數，可以實驗看看 S3 是不是也是這樣~
然後 region 在 .env 會統一寫成 `AWS_REGION` 這個變數（變數名稱符合要求他才會自己抓）

2024-12-01 02:37 UTC, amyhsu-o commented on backend/src/services/s3Service.js
> +                location: `https://${this._bucket}.s3.${process.env.S3_BUCKET_REGION}.amazonaws.com/${key}`,
（同上）AWS_REGION

2024-12-06 10:18 UTC, amyhsu-o approved these changes

2024-12-06 10:23 UTC, merged