Feature/yun si/cns 50 room stagging area
Esther125/CloudDrop pull request #33
Opened 2024-12-07 11:09 UTC by yun-si

## Change
- Add room's stage-area

## Test 
1. start frontend and backend
2. open two or more browser pages and join the same room

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/21b074f1-813b-47b4-9d07-fca2551a6b91">

### **Press "See Files"** then

right side was switch from chat to file

<img width="1462" alt="截圖 2024-12-07 晚上7 06 06" src="https://github.com/user-attachments/assets/13cab64d-8ddc-4f2a-a38b-46144ce5f08b">

### **if comment the data in files**

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/f0c774b3-befc-4fd2-aa46-a5ddfdc7da00">

2024-12-10 16:13 UTC, amyhsu-o commented
1. 前端還沒設計離開房間的機制，所以加入過就不能再創建其他房間（也要記得 call socket 的 leave chatroom）
2. 後端還沒設計斷線的時候自動通知房間內其他人，有人離開房間（這個我可以再開一張票來加）
3. 邀請碼輸入
(1) 可以改成大小寫不敏感
(2) 再點開的時候可以自動把之前的輸入清掉
4. 後端 .env.example 記得加 FRONTEND_BASE_URL，前端記得加 VITE_CHAT_SERVER_URL（如果在別的地方有加了，merge 的時候再注意一下）

2024-12-10 17:21 UTC, amyhsu-o commented
發現如果網頁放著很久，其實 websocket 中間會經歷斷線重連（socket.io 已經自動處理掉了，所以沒有在 code 裡寫出來），但在重連過後後端裡該 socket 在哪一個 room 裡的資訊就會被清掉了（因為重連就是新的 socket），所以後面會收不到跟那個 room 有關的事件

會再跟上面的 2. 一起改

2024-12-10 17:33 UTC, amyhsu-o requested changes
1. 前端還沒設計離開房間的機制，所以加入過就不能再創建其他房間（也要記得 call socket 的 leave chatroom）
2. 後端還沒設計斷線的時候自動通知房間內其他人，有人離開房間（這個我可以再開一張票來加）
3. 邀請碼輸入
(1) 可以改成大小寫不敏感
(2) 再點開的時候可以自動把之前的輸入清掉
4. 後端 .env.example 記得加 FRONTEND_BASE_URL，前端記得加 VITE_CHAT_SERVER_URL（如果在別的地方有加了，merge 的時候再注意一下）

2024-12-10 17:33 UTC, amyhsu-o commented
發現如果網頁放著很久，其實 websocket 中間會經歷斷線重連（socket.io 已經自動處理掉了，所以沒有在 code 裡寫出來），但在重連過後後端裡該 socket 在哪一個 room 裡的資訊就會被清掉了（因為重連就是新的 socket），所以後面會收不到跟那個 room 有關的事件

會再跟上面的 2. 一起改，但有可能會影響到前端的部分，我再確認一下再看怎麼調整

2024-12-11 11:27 UTC, yun-si commented
> 發現如果網頁放著很久，其實 websocket 中間有可能會經歷斷線重連（socket.io 已經自動處理掉了，所以沒有在 code 裡寫出來），但在重連過後後端裡該 socket 在哪一個 room 裡的資訊就會被清掉了（因為重連就是新的 socket），所以後面會收不到跟那個 room 有關的事件。
> 
> 會再跟上面的 2. 一起改，但有可能會影響到前端的一些部分，我再確認一下看怎麼調整 （目前想法，-- 擇一
> 
> 1. 從 **redis** 抓用戶在哪個 room 的資料，重連的時候後端自動幫她重新 join room。但是目前 redis 好像不會限制一個 user 只在一個 room 嗎 (?) 這個做法是可以不要動到前端的
> 2. 如果 redis 沒有限制的話，那可能就得要改到前端，可能是從 **socket 連線的時候的 auth** 那邊去加東西，變成要自己去做斷線重連的管理，不能讓 socket.io 自動做。這個我覺得比較麻煩，目前也還沒有很確定這樣行不行。）

目前有限制一個 user 只能在一個 room 裡
可以用 userId 抓
<img width="732" alt="image" src="https://github.com/user-attachments/assets/b7fe735f-b2e3-48e5-9c42-fbbe4191d448">

2024-12-11 11:32 UTC, amyhsu-o submitted a review, later dismissed

2024-12-11 11:33 UTC, amyhsu-o approved these changes, later dismissed

2024-12-11 11:51 UTC, closed without merging