Feature/yu mei/cns 42 be jwt fe register login out
Esther125/CloudDrop pull request #38
Opened 2024-12-08 12:40 UTC by amyhsu-o

## Changes
### Backend
1. give JWT token when login (put it in cookie), take back after a given time period or when user logout
2. add middleware `jwtMiddleware`, can be use for any API that need the token to get userID, username

### Frontend
1. add login, logout, register page
2. add logic to check the JWT token

## Test

### Setup

**Backend**
1. follow [docs\project_setup\aws_access_key_setup.md](https://github.com/Esther125/CloudDrop/blob/feature/yu-mei/CNS-43-doc-aws-iam-user-setup/docs/project_setup/aws_access_key_setup.md) to set up AWS access key info in .env
2. 
```bash
cd backend
npm install
npm start
```

**Frontend**
```bash
cd frontend
npm install
npm run dev
```

### Test
1. if the user doesn't login, when he/she tries to click on storage, history, logout page, the login request will pop out.
![image](https://github.com/user-attachments/assets/6b349e70-20ab-4844-91bb-ffa7e01f2d74)

2. register page
![image](https://github.com/user-attachments/assets/fe7ff890-8097-4683-9095-0417dcc86058)

3. after register and login, the user can enter storage, history, logout page
![image](https://github.com/user-attachments/assets/85ba2e4a-161b-40f4-bf8d-9ff80812022e)
![image](https://github.com/user-attachments/assets/458f775b-ab83-4dbe-a8a8-3882991bf7d4)
![image](https://github.com/user-attachments/assets/480bb215-72e6-4c69-a4ca-575ccf4a0de0)

4. logout popout
![image](https://github.com/user-attachments/assets/c19e3d53-7432-471d-a7fb-03fdafaa2f80)

5. after logout, when the user tries to click on storage, history, logout page, the login request will pop out again

6. JWT token will last for 7 days, so in that time period, users are not required to re-login

2024-12-15 11:49 UTC, amyhsu-o commented
TODO:
1. 登入登出彈出視窗，成功後停留幾秒自動消失
2. 登入後替換掉前端原本的 userID

（已完成）

2024-12-19 14:33 UTC, amyhsu-o commented
目前前端還有一些 bug，目前可以先從
1. login / logout 的彈出視窗正確出現、消失
2. userID 有沒有正確替換 -- 瀏覽器最下面的 bar、後端的 console
這兩項來確認 JWT 的功能

2024-12-19 16:36 UTC, yun-si approved these changes, later dismissed

2024-12-19 16:46 UTC, yun-si requested changes

2024-12-19 16:46 UTC, yun-si commented on frontend/src/App.vue
> +        sessionStorage.setItem('userId', userId); // Save to SessionStorage
這邊會導致同瀏覽器其他網頁重整後
被判定有登入
但因為已經有 storedUserId 所以拿不到 auth-check 的 id

2024-12-19 16:50 UTC, yun-si commented on frontend/src/App.vue
> +        sessionStorage.setItem('userId', userId); // Save to SessionStorage
這樣會導致其他分頁登入了
但這這一個分頁因為已經有 storedUserId
所以被判定有登入
但 user id 沒有抓到正確的
因為在 if 就被擋掉了

2024-12-20 13:17 UTC, yun-si requested changes
logout 之後會有新的  userId
但網頁重整之後 底下的 bar 的 id 會不見

2024-12-21 01:41 UTC, yun-si requested changes
其他都很讚！！！
你真的好厲害

2024-12-21 01:41 UTC, yun-si commented on backend/src/services/dynamodbService.js
log 的部分改一下！
不小心用回 console.log 了

2024-12-21 01:41 UTC, yun-si commented on backend/src/services/dynamodbService.js
這個檔案少這麼多東西是正常的嗎？
getTransferRecord 也被拿掉了

<img width="847" alt="image" src="https://github.com/user-attachments/assets/2c9c4a2e-331b-493e-a582-2d5818425e73" />

2024-12-21 01:41 UTC, yun-si commented on frontend/src/App.vue
> +    });
這段是用 web socket 去問使用者是不是正在一間房間內嗎？

2024-12-21 01:41 UTC, yun-si commented on frontend/src/App.vue
關 room modal 得時候沒有清到輸入

<img width="513" alt="image" src="https://github.com/user-attachments/assets/1744a4cc-a961-4005-88ab-17736e1faa7f" />

2024-12-21 01:48 UTC, amyhsu-o commented on backend/src/services/dynamodbService.js
被誤刪了，有加回去了

2024-12-21 01:48 UTC, amyhsu-o commented on backend/src/services/dynamodbService.js
是因為誤刪造成的~

2024-12-21 01:50 UTC, amyhsu-o commented on frontend/src/App.vue
> +    });
對，因為發現之前在 websocket 那邊做斷線重連後，前端不知道他已經有在房間裡了，這邊 store.clientSocket`.once` 就是只會接收一次就會關掉了，後面有再開一個給平常用的

2024-12-21 07:42 UTC, yun-si approved these changes
👍🏼

2024-12-21 07:54 UTC, merged