Feature/jlin/cns 54 staging area page
Esther125/CloudDrop pull request #59
Opened 2024-12-22 01:58 UTC by JLin056

## Change
- Add staging area page

## Test
1. start backend and frontend
2. click Temporary Storage
3. 
- if user doesn't have file in s3
![image](https://github.com/user-attachments/assets/b21229c0-cde0-4393-a1e8-60346da07ac9)
- if user have many file in s3
(Comment out line 9 and uncomment line 10.)
```
// const userID = store.user.id;
const userID = '12346';
```
![image](https://github.com/user-attachments/assets/aa4019d5-346a-456a-b6d1-4e1659ae2708)
and Scroll down, you will see more file
![image](https://github.com/user-attachments/assets/288e9c4b-8871-4898-b4ad-71cbbd552a9f)
4. click 下載 button, then download the file
![image](https://github.com/user-attachments/assets/5f02e20b-5315-4226-80e9-91a897eba37a)

2024-12-22 06:12 UTC, amyhsu-o requested changes

2024-12-22 06:12 UTC, amyhsu-o commented on backend/src/services/s3Service.js
getFileList retrieve 回來的結果有可能照時間排序嗎? 還是 s3 沒有支援這樣? 不然前端顯示起來會不知道剛剛上傳的跑去哪裡了

2024-12-22 06:12 UTC, amyhsu-o commented on frontend/src/views/StorageView.vue
> +            window.open(data.url, '_blank');
這邊可以用 _parent 才不會畫面跳出去又回來或閃一下~

2024-12-22 06:12 UTC, amyhsu-o commented on frontend/src/views/StorageView.vue
> +    border-radius: 6px;
![image](https://github.com/user-attachments/assets/32cc21fb-2e92-4069-95a0-f167945d50d0)
(之前有點想調，但來不及做的)
就是這個 scrollbar 被下面的 navbar 遮住了，從上面看的話她應該要是圓弧形的，如果想要可以研究一下

(如果有研究出來，歷史紀錄那一頁可以幫我順便一起調 xd)

2024-12-22 06:12 UTC, amyhsu-o commented on frontend/src/assets/images/download-icon.svg
沒用到可刪

2024-12-22 06:12 UTC, amyhsu-o commented on frontend/src/views/StorageView.vue
> +            </div>
可以放個時間戳和快過期的提醒符號之類的，或是檔案大小甚麼的感覺也可以放，不然抓出來的資料都沒有用到~ 

覺得時間戳和快過期的提醒符號蠻重要

2024-12-22 06:12 UTC, amyhsu-o commented on backend/test/s3.integration.test.js
> +        const fileList = await s3Service.getFileList(mockUserId);
![image](https://github.com/user-attachments/assets/00d39b61-3970-486b-81f1-788125fb5a16)

這個會報錯，應該是沒放到 type

2024-12-23 08:30 UTC, JLin056 commented on backend/src/services/s3Service.js
這個想跟 新開的票一起修～

2024-12-23 13:15 UTC, JLin056 commented
有改完了～
- [x] 下載button 跳閃
- [x] scrollbar 上移（原本會被 footer 遮住）=> 檔案暫存區頁、歷史紀錄頁
- [x] 移除 download-icon
- [x] 距離到期日還剩幾天
- [x] 檔案大小
- [x] 移除 s3.integration.test.js  
- [ ] 時間排序問題 => 會在 CNS-82 那張票一起改

![image](https://github.com/user-attachments/assets/fc05972d-a46f-430c-a869-53347f8cf325)

2024-12-23 13:40 UTC, yun-si requested changes

2024-12-23 13:40 UTC, yun-si commented on frontend/src/views/StorageView.vue
> +        <h2 class="m-0 pt-3 pb-0">檔案暫存區</h2>
可以設定 mb-2 之類的讓標題跟底下的框框有一些間隙

2024-12-23 13:52 UTC, yun-si submitted a review, later dismissed

2024-12-23 13:59 UTC, yun-si approved these changes, later dismissed

2024-12-23 18:38 UTC, amyhsu-o requested changes

2024-12-23 18:38 UTC, amyhsu-o commented on frontend/src/views/StorageView.vue
> +const totalFilesCount = ref(0);
這個如果一開始設 0 的話，這樣畫面都會閃一下 "暫無檔案" 後才會跳內容，可以預設 -1，這樣不會進來的時候閃一下（可以參考歷史紀錄那邊的樣子）

2024-12-24 07:05 UTC, JLin056 commented on frontend/src/views/StorageView.vue
> +const totalFilesCount = ref(0);
改好了～原本後端沒有回傳 檔案數量，所以是用前端去計算，但這樣預設 -1 再去加 沒有正確解決。
所以 目前**修了後端讓他顯示 檔案數量**，該用戶沒檔案( 'No Files found' ) 設置為 200，並回傳 message。

2024-12-27 15:45 UTC, amyhsu-o approved these changes

2024-12-27 15:46 UTC, merged